### ISSUE TITLE
Credentials priority

### ISSUE THREAD

**Issue by vdksystem** [int128/kaniko-action#384]
I run kaniko on custom runner within EKS cluster. 
Use OIDC to authenticate.
Kaniko throws me Unauthorised error.
Added a debug step to check `aws Sts get-caller-identity`, getting what I expect.

Switched to default runner (ubuntu-latest, provided by GitHub) - build succeeded.

It looks like kaniko uses node default permissions instead of session permissions obtained by login.

Pipeline:
```
jobs:
  build:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: 'arn:aws:iam::ACCOUNT:role/github-action-test-role'
          aws-region: us-east-1
      - uses: aws-actions/amazon-ecr-login@main
        id: ecr
        with:
          registries: 'ACCOUNT'
      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ${{ steps.ecr.outputs.registry }}/${{ github.event.repository.name }}
      - name: debug
        run: |
          pip install awscli
          aws sts get-caller-identity
      - uses: int128/kaniko-action@v1
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache: false
```
