### ISSUE TITLE
Kaniko IMDSv2 Access Issue on Self-Hosted Runner: "Failed to refresh cached credentials, no EC2 IMDS role found"

### ISSUE THREAD

**Issue by BMelekAlan** [int128/kaniko-action#866]
When using Kaniko to push Docker images to Amazon ECR on a self-hosted runner managed by Actions Runner Controller, I encounter an error related to IMDSv2 access. The error states: `failed to refresh cached credentials, no EC2 IMDS role found.`

If IMDSv2 is made optional, or when using a GitHub-hosted runner (ubuntu-latest), the workflow completes successfully. This suggests the issue is tied to IMDSv2's strict requirement on the self-hosted runner.

Expected Behavior:
Kaniko should successfully retrieve the IMDSv2 token, use the IAM role assigned to the pod, and push the image to Amazon ECR without requiring IMDSv2 to be optional.

Observed Behavior:
Kaniko fails to authenticate and push to Amazon ECR when IMDSv2 is required. The error message is:

`failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, canceled, context deadline exceeded`

**Configuration**
```
  build:
    runs-on: k8s-runner-develop
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Docker Meta for Base Images
        id: meta_tightly_base
        uses: docker/metadata-action@v4
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/xxxx/base/xxxx
          flavor: |
            latest=${{ github.event.inputs.tag_as_latest }}
          tags: |
            type=raw,value=${{ github.event.inputs.tag_name }}
            
      - name: Build and push Base Images
        if: github.event_name != 'pull_request'
        id: docker_build-base-images
        uses: int128/kaniko-action@v1
        with:
          push: true
          executor: gcr.io/kaniko-project/executor:v1.23.2
          tags: ${{ steps.meta_tightly_base.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          context: "./"
          file: "./Dockerfile"
          cache: false
          verbosity: debug
```
**Logs:**
```
DEBU[0000] Copying file /kaniko/action/context/Dockerfiles/atlantis.Dockerfile to /kaniko/Dockerfile
DEBU[0005] Could not fetch credentials for cache prefix, disabling cache  error="failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, canceled, context deadline exceeded"
DEBU[0005] Retrieving credentials                        region=us-east-1 registry=<account-id> serverURL=<account-id>.dkr.ecr.us-east-1.amazonaws.com service=ecr
DEBU[0005] Calling ECR.GetAuthorizationToken             registry=<account-id>
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "<account-id>.dkr.ecr.us-east-1.amazonaws.com/xxxx/base/xxxx:latest": POST https://<account-id>.dkr.ecr.us-east-1.amazonaws.com/v2/xxxxx/base/xxxx/blobs/uploads/: unexpected status code 401 Unauthorized: Not Authorized

```
